name             'ratchet'
maintainer       'Ryan Hass'
maintainer_email 'ryan a t invalidchecksum d ot n et'
license          'Apache 2.0'
description      'Installs/Configures ratchet'
long_description 'Installs/Configures ratchet'
version          '0.1.0'

depends 'apt'
depends 'build-essential'
depends 'nodejs'
depends 'git'
